apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: image-name
      type: string
    - name: image-tag
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      script: |
        /kaniko/executor --dockerfile=Dockerfile --destination=$(params.image-name):$(params.image-tag) --context=$(workspaces.source.path)

