apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ci-pipeline-run-
spec:
  pipelineRef:
    name: tekton-pipeline
  params:
    - name: git-url
      value: {{ .Values.git.url }}
    - name: image-tag
      value: $(context.pipelineRun.name) # Automatically uses the PipelineRun name as tag
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  serviceAccountName: tekton-sa

