apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: default
secrets:
  - name: git-ssh-key
  - name: ghcr-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services", "persistentvolumeclaims", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "tasks", "taskruns", "pipelines"]
    verbs: ["get", "list", "create", "delete", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-cluster-role
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: default

